# .github/workflows/black.yml
name: Black Formatter Check
on:
  pull_request:
    branches: [main]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@25.1.0  
        with:
          use_pyproject: true